//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClippyAI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClippyAI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mode:.
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Content:.
        /// </summary>
        internal static string ClipboardContent {
            get {
                return ResourceManager.GetString("ClipboardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClippyAI.
        /// </summary>
        internal static string ClippyAI {
            get {
                return ResourceManager.GetString("ClippyAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard (experimental).
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama URL:.
        /// </summary>
        internal static string OllamaUrl {
            get {
                return ResourceManager.GetString("OllamaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response:.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a model!.
        /// </summary>
        internal static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a task!.
        /// </summary>
        internal static string SelectTask {
            get {
                return ResourceManager.GetString("SelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email..
        /// </summary>
        internal static string Task_1 {
            get {
                return ResourceManager.GetString("Task_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and request a confirmation..
        /// </summary>
        internal static string Task_10 {
            get {
                return ResourceManager.GetString("Task_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and request a rescheduling..
        /// </summary>
        internal static string Task_11 {
            get {
                return ResourceManager.GetString("Task_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain what it is as precisely as possible..
        /// </summary>
        internal static string Task_12 {
            get {
                return ResourceManager.GetString("Task_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain where the error lies and how to fix it..
        /// </summary>
        internal static string Task_13 {
            get {
                return ResourceManager.GetString("Task_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain how it can be improved..
        /// </summary>
        internal static string Task_14 {
            get {
                return ResourceManager.GetString("Task_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Task.
        /// </summary>
        internal static string Task_15 {
            get {
                return ResourceManager.GetString("Task_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate this text to English..
        /// </summary>
        internal static string Task_16 {
            get {
                return ResourceManager.GetString("Task_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate this text to German..
        /// </summary>
        internal static string Task_17 {
            get {
                return ResourceManager.GetString("Task_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate this text to French..
        /// </summary>
        internal static string Task_18 {
            get {
                return ResourceManager.GetString("Task_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate this text to Spanish..
        /// </summary>
        internal static string Task_19 {
            get {
                return ResourceManager.GetString("Task_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a detailed response to the email..
        /// </summary>
        internal static string Task_2 {
            get {
                return ResourceManager.GetString("Task_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and tell that you already solved the problem..
        /// </summary>
        internal static string Task_20 {
            get {
                return ResourceManager.GetString("Task_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and graciously agree..
        /// </summary>
        internal static string Task_3 {
            get {
                return ResourceManager.GetString("Task_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and politely decline..
        /// </summary>
        internal static string Task_4 {
            get {
                return ResourceManager.GetString("Task_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and request more information..
        /// </summary>
        internal static string Task_5 {
            get {
                return ResourceManager.GetString("Task_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and request a meeting appointment..
        /// </summary>
        internal static string Task_6 {
            get {
                return ResourceManager.GetString("Task_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and say that you will take care of the problem..
        /// </summary>
        internal static string Task_7 {
            get {
                return ResourceManager.GetString("Task_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and say that you cannot solve the problem and refer to Person X..
        /// </summary>
        internal static string Task_8 {
            get {
                return ResourceManager.GetString("Task_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a response to the email and request a feedback..
        /// </summary>
        internal static string Task_9 {
            get {
                return ResourceManager.GetString("Task_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your task has been completed and copied to the clipboard!
        ///Result:
        ///.
        /// </summary>
        internal static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What I should do for you:.
        /// </summary>
        internal static string TaskLabel {
            get {
                return ResourceManager.GetString("TaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string TaskStart {
            get {
                return ResourceManager.GetString("TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TaskStop {
            get {
                return ResourceManager.GetString("TaskStop", resourceCulture);
            }
        }
    }
}
